spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: default-server
          uri: lb://DEFAULT-SERVER
          predicates:
            - Path=/v1/default/**
          filters:
            - RewritePath=/v1/default(?<segment>/?.*), $\{segment}

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/v1/product/**
          filters:
            - RewritePath=/v1/product(?<segment>/?.*), $\{segment}

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/v1/inventory/**
          filters:
            - RewritePath=/v1/inventory(?<segment>/?.*), $\{segment}

        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/v1/delivery/**
          filters:
            - RewritePath=/v1/delivery(?<segment>/?.*), $\{segment}

        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/v1/hub/**
          filters:
            - RewritePath=/v1/hub(?<segment>/?.*), $\{segment}

        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/v1/auth/**
          filters:
            - 'RewritePath=/v1/auth/(?<path>.*), /\${path}'

        - id: user-service-user
          uri: lb://user-service
          predicates:
            - Path=/v1/user/**
          filters:
            - 'RewritePath=/v1/user/(?<path>.*), /\${path}'
